name: shop_management_app
description: A shop management application with multiple modules
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5  # GetX for state management
  fl_chart: ^0.62.0  # For line charts
  shared_preferences: ^2.1.1  # For local storage
  google_fonts: ^4.0.4  # For custom fonts
  cupertino_icons: ^1.0.5
  intl: ^0.18.1  # For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
